"""Tests for XYZ text export used by save and clipboard actions."""

import pytest
from rdkit import Chem
from rdkit.Geometry import Point3D

from molrecognizer.core.xyz import BOHR_PER_ANGSTROM, mol_to_xyz_string


def _molecule_with_conformer():
    molecule = Chem.AddHs(Chem.MolFromSmiles("C"))
    conformer = Chem.Conformer(molecule.GetNumAtoms())
    for index in range(molecule.GetNumAtoms()):
        conformer.SetAtomPosition(index, Point3D(float(index), 0.0, -1.0))
    molecule.AddConformer(conformer)
    return molecule


def test_xyz_string_has_header_atoms_and_trailing_newline():
    text = mol_to_xyz_string(_molecule_with_conformer())
    lines = text.splitlines()

    assert lines[0] == "5"
    assert lines[1] == "Generated by MolRecognizer (unit: angstrom)"
    assert lines[2].split() == ["C", "0.00000000", "0.00000000", "-1.00000000"]
    assert text.endswith("\n")


def test_xyz_bohr_conversion():
    text = mol_to_xyz_string(_molecule_with_conformer(), unit="bohr")
    hydrogen = text.splitlines()[3].split()

    assert float(hydrogen[1]) == pytest.approx(BOHR_PER_ANGSTROM)
    assert float(hydrogen[3]) == pytest.approx(-BOHR_PER_ANGSTROM)
