"""3D structure generation and XYZ file export."""

from __future__ import annotations

from rdkit import Chem
from rdkit.Chem import AllChem

BOHR_PER_ANGSTROM = 1.8897259886


def generate_3d(smiles: str) -> Chem.Mol:
    """Generate a 3D conformer from a SMILES string.

    Returns an RDKit Mol with explicit Hs and a 3D conformer.
    Raises RuntimeError if embedding fails.
    """
    rdmol = Chem.MolFromSmiles(smiles)
    if rdmol is None:
        raise ValueError(f"Cannot parse SMILES: {smiles!r}")
    rdmol = Chem.AddHs(rdmol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(rdmol, params)
    if result == -1:
        raise RuntimeError("Failed to generate 3D coordinates")
    # Optimise geometry — MMFF preferred, UFF as fallback
    try:
        AllChem.MMFFOptimizeMolecule(rdmol, maxIters=500)
    except Exception:
        try:
            AllChem.UFFOptimizeMolecule(rdmol, maxIters=500)
        except Exception:
            pass  # use un-optimised coordinates
    return rdmol


def mol_to_xyz_string(rdmol: Chem.Mol, unit: str = "angstrom") -> str:
    """Convert an RDKit mol with a 3D conformer to an XYZ-format string.

    Args:
        rdmol: RDKit Mol with at least one conformer.
        unit: ``"angstrom"`` (default) or ``"bohr"``.
    """
    conf = rdmol.GetConformer()
    n = rdmol.GetNumAtoms()
    factor = BOHR_PER_ANGSTROM if unit == "bohr" else 1.0
    lines = [str(n), f"Generated by MolRecognizer (unit: {unit})"]
    for i in range(n):
        atom = rdmol.GetAtomWithIdx(i)
        pos = conf.GetAtomPosition(i)
        x, y, z = pos.x * factor, pos.y * factor, pos.z * factor
        lines.append(f"{atom.GetSymbol():2s} {x:15.8f} {y:15.8f} {z:15.8f}")
    return "\n".join(lines) + "\n"


def mol_to_atoms_bonds(rdmol: Chem.Mol):
    """Extract atom and bond lists for the 3D viewer.

    Returns:
        (atoms, bonds) where *atoms* is a list of
        ``(element, x, y, z)`` tuples and *bonds* is a list of
        ``(begin_idx, end_idx, order)`` tuples (order: 1, 2, or 3).
    """
    conf = rdmol.GetConformer()
    atoms = []
    for i in range(rdmol.GetNumAtoms()):
        atom = rdmol.GetAtomWithIdx(i)
        pos = conf.GetAtomPosition(i)
        atoms.append((atom.GetSymbol(), pos.x, pos.y, pos.z))
    bonds = []
    for bond in rdmol.GetBonds():
        order = int(round(bond.GetBondTypeAsDouble()))
        order = max(1, min(3, order))
        bonds.append((bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), order))
    return atoms, bonds
